name: Continuous Integration

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        build_configuration:
          - target: x86_64-unknown-linux-gnu
            cpu: native
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ matrix.build_configuration.target }}-${{ matrix.build_configuration.cpu }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'false'
          set-safe-directory: 'true'

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.KAKADU_SSH_KEY }}"

      - run: git submodule update --init
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - uses: swatinem/rust-cache@v2
        with:
          prefix-key: 'v0-rust-${{ matrix.build_configuration.target }}-${{ matrix.build_configuration.cpu }}'

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: ${{ matrix.build_configuration.target }}
          components: llvm-tools-preview

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest, cargo-llvm-cov

      - name: Run tests
        run: |
          cargo llvm-cov nextest --target ${{ matrix.build_configuration.target }}
          cargo llvm-cov report --lcov --output-path lcov.info
          cargo llvm-cov --text  >> $GITHUB_STEP_SUMMARY
        env:
          RUSTFLAGS: "-Ctarget-cpu=${{ matrix.build_configuration.cpu }}"
          CARGO_TERM_COLOR: always
